services:
  - type: redis
    name: private-redis
    ipAllowList: []
    plan: starter

  - type: worker
    name: sidekiq
    env: docker
    dockerfilePath: ./forem/Dockerfile
    dockerContext: ./forem
    dockerCommand: ./scripts/sidekiq.sh
    plan: starter
    autoDeploy: false
    envVars:
      - fromGroup: rails
      - key: REDIS_HOST
        fromService:
          name: private-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: private-redis
          type: redis
          property: port

      - key: DATABASE_URL
        fromDatabase:
          name: forem
          property: connectionString

  - type: web
    name: forem
    env: docker
    dockerfilePath: ./forem/Dockerfile
    dockerContext: ./forem
    dockerCommand: ./scripts/rails.sh
    plan: standard
    autoDeploy: false
    disk:
      name: data
      mountPath: /opt/apps/forem/public/uploads
      sizeGB: 10
    envVars:
      - fromGroup: rails
      - key: REDIS_HOST
        fromService:
          name: private-redis
          type: redis
          property: host
      - key: REDIS_PORT
        fromService:
          name: private-redis
          type: redis
          property: port

      - key: DATABASE_URL
        fromDatabase:
          name: forem
          property: connectionString

databases:
  - name: forem
    plan: starter

envVarGroups:
  - name: rails
    envVars:
      - key: APP_PROTOCOL
        value: "https://"
      - key: RAILS_ENV
        value: production
      - key: NODE_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: 1
      - key: RAILS_SERVE_STATIC_FILES
        value: 1
      - key: RAILS_MAX_THREADS
        value: 1
      - key: WEB_CONCURRENCY
        value: 2
      - key: RACK_TIMEOUT_WAIT_TIMEOUT
        value: 100_000
      - key: RACK_TIMEOUT_SERVICE_TIMEOUT
        value: 100_000

      - key: FOREM_OWNER_SECRET
        generateValue: true

      - key: SECRET_KEY_BASE
        generateValue: true

      - key: COMMUNITY_NAME
        value: Forem on Render

      - key: CLOUDINARY_API_KEY
        value: configure_cloudinary_to_enable_uploaded_images
      - key: CLOUDINARY_API_SECRET
        value: configure_cloudinary_to_enable_uploaded_images
      - key: CLOUDINARY_CLOUD_NAME
        value: configure_cloudinary_to_enable_uploaded_images

      - key: SENDGRID_API_KEY
        sync: false # set to your Sendgrid SMTP Relay API key

      - key: DEFAULT_EMAIL
        sync: false # set to the email configured with Sendgrid

      - key: APP_DOMAIN
        sync: false # set this to your custom domain or the rails service .onrender domain

